version: "3"

services:
  app:
    container_name: pgunittest_${PROJECT_NAME}_app
    image: registry.t.cpm.dev/library/pgunittestextras:master20201118102316
    entrypoint: /sh/runtests.sh
    environment:
      - POSTGRES_DB=mpoint
      - APPROOT=$APP_ROOT
      - WEBROOT=$APP_ROOT/webroot
      - PHPUNIT_EXEC_PATH=$APP_ROOT/vendor/bin/phpunit
      - PHPUNIT_CONFIG_PATH=$APP_ROOT/phpunit.xml
      - LIQUIBASE_CHANGELOG_ROOT=/liquibase/db
      - SERVER_NAME=mpoint.local.cellpointmobile.com
      - APP_LOG_FOLDER_PATH=$APP_ROOT/log
      - LOG_OUTPUT_METHOD=1
      - XDEBUG_CONFIG=remote_enable=1 remote_autostart=1 remote_port=9001 remote_host=${HOST_IP}
      - PHP_IDE_CONFIG=serverName=mpoint.local.cellpointmobile.com
    volumes: 
      - ./api:/opt/cpm/mPoint/api
      - ./conf:/opt/cpm/mPoint/conf
      - ./log:/opt/cpm/mPoint/log
      - ./test:/opt/cpm/mPoint/test
      - ./vendor:/opt/cpm/mPoint/vendor
      - ./webroot:/opt/cpm/mPoint/webroot
      - ./liquibase/src/main/resources/liquibase/db:/liquibase/db
      - ./phpunit.xml:/opt/cpm/mPoint/phpunit.xml