
/* ========== ALTER TABLE FOR MERCHANT ACCOUNT TO HAVE PASSWORD OF 4000 CHARS START ====== */
ALTER TABLE Client_Ownr.MerchantAccount_Tbl MODIFY passwd VARCHAR2(4000);
ALTER TABLE Client_Ownr.MerchantAccount_Tbl MODIFY name VARCHAR2(100);
/* ========== ALTER TABLE FOR MERCHANT ACCOUNT TO HAVE PASSWORD OF 4000 CHARS END ====== */
