/*----------10018----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1046;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1066;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1336;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1381;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1203;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1061;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1043;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1214;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1068;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1162;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1398;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1064;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1202;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1053;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1048;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1047;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1056;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1058;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1063;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1051;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1059;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1044;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1045;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1062;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1213;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1067;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1065;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1215;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1049;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1057;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1060;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1201;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1050;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1163;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1149;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 36 as walletid , dccenabled from client.cardaccess_tbl where id = 1052;


/*----------10020----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1076;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1077;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1078;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1088;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1089;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1082;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1083;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1086;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1087;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1122;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1123;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1090;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1091;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1094;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1095;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1098;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1099;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1102;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1103;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1110;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1111;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1116;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1117;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1114;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1115;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1124;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1125;


/*----------10022----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1192;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 44 as walletid , dccenabled from client.cardaccess_tbl where id = 1193;



/*----------10061----------*/
-- Confusion 10061

-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1434;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1156;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1157;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1435;


/*----------10066----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1209;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1180;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1179;

/*----------10069----------*/
-- Confusion 10069

-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1292;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1295;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1289;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1290;
-- insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1291;

/*----------10070----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1207;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1208;

/*----------10071----------*/
-- Confusion 10071


/*----------10073----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1331;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1330;

/*----------10074----------*/

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1458;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1349;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1350;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1351;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1261;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1469;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1262;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1263;

/*----------10078----------*/

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1444;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1446;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1447;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1451;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1484;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1453;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1454;

/*----------10079----------*/

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1477;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1478;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1475;

/*----------10081----------*/

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1556;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1559;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1560;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1562;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1579;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1532;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1575;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1576;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1580;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1538;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1577;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1578;


/*----------10089----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1590;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1588;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1589;


/*----------10090----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1607;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1605;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1606;


/*----------10091----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1672;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1676;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1677;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1669;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1680;



/*----------10100----------*/
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1626;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1629;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1632;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1635;

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1627;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1630;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1633;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1636;

insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1625;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1628;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1631;
insert into client.cardaccess_tbl (clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, walletid, dccenabled) select clientid, cardid, pspid, countryid, psp_type, installment, capture_method, capture_type, 14 as walletid , dccenabled from client.cardaccess_tbl where id = 1634;