<?php
/**
 * User: jot
 * Date: 24-03-15
 * Time: 19:46
 */

require_once __DIR__. '/authorizeAPITest.php';

class NetaxeptAuthorizeAPITest extends AuthorizeAPITest
{
    public function testSuccessfulAuthorize()
    {
         $this->markTestIncomplete("Skipped as the test case tests an old integration which is no longer supported by NetAxept. To remedy this, the new NetAxept integration from branch: release/v2.02 needs to be merged in");
		/* Setup netaxept simulator, through error file mark */
		// $config = new stdClass();
		// $config->AmountCaptured = 0;
		// trigger_error("NETAXEPT SIMULATOR CONFIG :: ". base64_encode(serialize($config) ) );

        // parent::testSuccessfulAuthorize(Constants::iNETAXEPT_PSP);
        $this->assertTrue(true);
    }

	public function testSuccessfulAuthorizeIncludingAutoCapture()
	{
	     $this->markTestIncomplete("Skipped as the test case tests an old integration which is no longer supported by NetAxept. To remedy this, the new NetAxept integration from branch: release/v2.02 needs to be merged in");
        $this->assertTrue(true);
		//TODO: Implement auto-capture test for Netaxept. This implies letting the Netaxept authorize simulator trigger a callback to mPoint
	}
    public function testSuccessfulAuthorizeWithCurrency()
    {
         $this->markTestIncomplete("Skipped as the test case tests an old integration which is no longer supported by NetAxept. To remedy this, the new NetAxept integration from branch: release/v2.02 needs to be merged in");
        $this->assertTrue(true);
        // TODO: Change the autogenerated stub
    }
}